name: tests
on: [push, pull_request]
jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [10.x, 12.x]
      fail-fast: false
    name: Run tests
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1.1.0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: hecrj/setup-rust-action@v1.3.3
        with:
          rust-version: stable
      - name: Bump inotify limit (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p;
      - name: ESLint & Prettier
        run: yarn lint
      - name: Unit Tests
        run: yarn test:unit
      - name: Integration Tests
        run: yarn test:integration-ci
      - name: Flow
        run: yarn flow check
